sugarcube-2:
  macros:

    # My macros
    relGain:
      description: "Changes relationships, needs first name (caps matter) and number"
      container: false
      parameters:
        - text &+ number
    
    printRelGain:
      description: "Prints whether or not a relationship increased"

    calcTime:
      description: "Calculates an increase of time in minutes"
    
    calcAttractiveness:
      description: "Maths out attractiveness"

    readBook:
      description: "Increments pages read and unlocks accordingly"

    foundItem:
      description: "Picks up an item and notifies player"

    speech:
      description: "Makes speech boxes. Takes one arg, either lowercase name of speaker or 'plr'"
      container: true
      parameters:
       - text |+ text

    tone:
      description: "Adds a color and italics as a tone for speech. Takes one arg, either 'neg' or 'pos'"
      container: true
      parameters:
       - text
      
    hovertip:
      description: "Makes a tooltip over whatever the tags contain. Add the tooltip arg as 'here is a tip'"
      container: true
      parameters:
       - text
      
    setStamina:
      description: "Sets the current stamina variable to args[0]"
      parameters:
        - number

    setLife:
      description: "Sets the current life variable to args[0]"
      parameters:
        - number

    setFocus:
      description: "Sets the current focus variable to args[0]"
      parameters:
        - number

    setSanity:
      description: "Sets the current sanity variable to args[0]"
      parameters:
        - number

    staminaUpdatePrint:
      description: "Prints out whether stamina is increased or decreased and by what amount. Then updates stamina pre to equal stamina cur. No args."

    # simple inventory macros
    item:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    consumable:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    description:
      parents:
        -item
        -consumable
        
    tags:
      parents:
        -item
        -consumable
        
    unique:
      parents:
        -item
        -consumable
        
    permanent:
      parents:
        -item
        -consumable
    
    newinv: {}
    
    pickup: {}
    drop: {}
    dropall: {}

    transfer: {}
    merge: {}
    unmerge: {}
    
    inv: {}
    take : {}
    give : {}
    
    # end simple inventory

    commentClean:
      description: "Prints a description of how clean, or not, your room is."

    commentFloor:
      description: "Prints a description of your floor."

    commentDesk:
      description: "Prints a description of your desk."

    commentChair:
      description: "Prints a description of your chair."

    commentBed:
      description: "Prints a description of your bed."

    commentLight:
      description: "Prints a description of your room's lighting situation."

    searchForItem:
      description: "Searches the location for items, updates location item variable, increments time, adds item if found."
      parameters:
        - address &+ number &+ text &+ text