sugarcube-2:
  macros:

    # My macros
    relGain:
      description: "Changes relationships, needs first name (caps matter) and number"
      container: false
      parameters:
        - text &+ number |+ text
    
    printRelGain:
      description: "Prints whether or not a relationship increased"

    calcTime:
      description: "Calculates an increase of time in minutes, args0 for precise min, args1 for random amt, args3 false for no stamina drain i.e. <<calcTime 30 5 false>>"
    
    calcAttractiveness:
      description: "Maths out attractiveness"

    readBook:
      description: "Increments pages read and unlocks accordingly"

    foundItem:
      description: "Picks up an item and notifies player"

    randomEvent:
      description: 'Sets up random events for the current passage, takes one args for the default passage append, i.e. <<randomEvent Residence_Starr_Courtyard_Standard>>'

    enemyStatBars:
      description: 'Populates and updates enemy star bars during combat events, takes one args as critter ID, i.e. <<enemyStatBars aggressiveSquirrel>>'

    consolelog:
      description: 'Takes one or two args, make the first text and second variable. i.e. "result: " _args'

    speech:
      description: "Makes speech boxes. Takes one arg, either lowercase name of speaker or 'plr'"
      container: true
      parameters:
       - text |+ text

    tone:
      description: "Adds a color and italics as a tone for speech. Takes one arg, either 'neg' or 'pos'"
      container: true
      parameters:
       - text

    setStats:
      description: 'Sets stats like so, <<setStats (plr or npcname) (statname) (# amount, + or -)>>'
      parameters:
        - text |+ text |+ number

    statsComments:
      description: 'Updates stat comments on right UI bar, i.e. <<statsComments (stamina, life, focus, sanity)'
      parameters:
        - text
    
    castSpell:
      description: 'Takes in temp vars and casts spell, i.e. <<castSpell _target _duration _effect _enhancement>>'
      parameters:
        - text &+ text &+ text &+ text
      
    hovertip:
      description: "Makes a tooltip over whatever the tags contain. Add the tooltip arg as 'here is a tip'"
      container: true
      parameters:
       - text

    GenerateCourseTbl:
      description: "Generates both schedule cell info, hovertip for the course, and a link if location is unlocked."

    ClassWarning:
      container: true
      description: "Generates a message for a class if you are not in the _args labeled classroom."

    TimeCheck:
      container: true
      description: "Takes multiple possible args to determine if something should happen according to time."
      parameters:
       - number &+ number |+ text |+ text |+ text |+ text

    Player:
      description: "Takes one arg, first, formal, or full and prints the appropriate style of the player's name. Arg two is p, to add a period after the name"
      parameters:
       - text |+ text
      
    SetTime:
      description: "Takes one arg, for the exact hour to move time forward to. Uses calcTime w/o stamina drain."
      parameters:
       - text

    ClassLectures:
      description: "Takes on arg, the variable name for a course then <<include>> the course passage. Also increments for the next lecture."
      parameters:
       - text

    # simple inventory macros
    item:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    consumable:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    description:
      parents:
        -item
        -consumable
        
    tags:
      parents:
        -item
        -consumable
        
    unique:
      parents:
        -item
        -consumable
        
    permanent:
      parents:
        -item
        -consumable
    
    newinv: {}
    
    pickup: {}
    drop: {}
    dropall: {}

    transfer: {}
    merge: {}
    unmerge: {}
    
    inv: {}
    take : {}
    give : {}
    
    # end simple inventory

    roomComments:
      description: "Prints a description of items, clean, and furniture qualities, i.e. <<roomComments (clean, bed, chair, etc.)>>"
      parameters:
        - text

    searchForItem:
      description: "Searches the location for items, updates location item variable, increments time, adds item if found."
      parameters:
        - text &+ text &+ text &+ number

    processClean:
      description: 'Increments clean level of all rooms wkere clean is in the object by the number of passed minutes. No args.'

    statsChange:
      description: 'Prints stats changed and their amount where function is called, i.e. <<statsChange>>'

    discChange:
      description: 'Tracks and prints change in discipline levels where called, i.e. <<discChange>>'

    setDisc:
      description: 'Sets discipline level increase, with option for random discipline to be chosen, i.e. <<setDisc plr abjuration 0.43>>'

    Updates:
      description: 'Combines discChange and statsChange in one call, will be expanded with additional functions to be called on passage load, i.e. <<Updates>>'

    CombatStart:
      description: 'Begins combat sequence, needs one args for npc or critter object, i.e. <<CombatStart tinyImp>>'

    CombatEnd:
      description: 'Ends combat sequence, calculates loot, prints final result, i.e. <<CombatEnd>>'

    NpcAvailable:
      description: 'Runs the time and day check for npc conversations, optional event otherwise defaults to the npcs Random passage, i.e. <<NpcAvailable 1600 1700 janessa saturday CourseOverview>>'

    NpcRelationGreet:
      description: 'Sets an opening greeting from an npc, based on their personality, i.e. <<NpcRelationGreet janessa>>'

    dlg:
      container: true
      children: [level]
      
    level:
      container: true
      children: [line]
      parents: [dlg]

    line:
      container: true
      parents: [level]